spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/godel?serverTimezone=UTC
    username: root
    password: Java1234
---
logging:
  level:
    org.springframework.web: ERROR
    com.kashuba: DEBUG